### ISSUE TITLE
Does not compile on windows since 1.13

### ISSUE THREAD

**Issue by viceice** [uhop/node-re2#68]
Hi,

the current version does no longer compile on windows with latest node v12 lts.
See pr below for full error.

Most errors looks like: `D:\\a\\renovate\\renovate\\node_modules\\re2\\vendor\\re2\\stringpiece.h(138,31): error C2589: '(': illegal token on right side of '::' (compiling source file ..\\lib\\addon.cc) `

ref: renovatebot/renovate#6308

**Comment by uhop** [comment]
Have you tried the master?

**Comment by a-parser** [comment]
actually it's broken since 1.12.0

**Comment by uhop** [comment]
@viceice and @a-parser &mdash; please try 1.13.1 and let me know if it works for you.

If it breaks, please post the output here.

**Comment by a-parser** [comment]
1.13.1 compiles ok

**Comment by viceice** [comment]
Works, thanks for fast fix.
